version: "3.9"
services:
  api:
    image: evlit/flask_db:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - 80:80
    environment:
      - DB_USER=$DB_USER
      - DB_NAME=$DB_NAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOST=pg
    depends_on:
      - pg
  pg:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_NAME
